name: Android CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleGithub
    - name: Install jq
      run: sudo apt-get install jq
    - name: Parse build files
      id: apk
      run: |
        versionName=$(cat "app/build/outputs/apk/gh/github/output-metadata.json" | jq -r '.elements[0].versionName')
        versionCode=$(cat "app/build/outputs/apk/gh/github/output-metadata.json" | jq -r '.elements[0].versionCode')
        mkdir outputs
        mv "app/build/outputs/apk/gh/github/app-gh-github.apk" "outputs/v2er.apk"
        mv "app/build/outputs/apk/ghm/github/app-ghm-github.apk" "outputs/v2er-max.apk"
        echo "versionName=$versionName" >> $GITHUB_OUTPUT
        echo "versionCode=$versionCode" >> $GITHUB_OUTPUT
    - name: 发布版本
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.apk.outputs.versionName }}-${{ steps.apk.outputs.versionCode }}
        files: |
          outputs/v2er.apk
          outputs/v2er-max.apk
