name: Android CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  OUTPUT_DIR: "app/build/outputs/apk/github"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleGithub
    - name: Install jq
      run: sudo apt-get install jq
    - name: Parse build files
      id: apk
      run: |
        versionName=$(cat "${{ env.OUTPUT_DIR }}/output-metadata.json" | jq -r '.elements[0].versionName')
        versionCode=$(cat "${{ env.OUTPUT_DIR }}/output-metadata.json" | jq -r '.elements[0].versionCode')
        apkFile=$(cat "${{ env.OUTPUT_DIR }}/output-metadata.json" | jq -r '.elements[0].outputFile')
        mv "${{ env.OUTPUT_DIR }}/$apkFile" "${{ env.OUTPUT_DIR }}/v2er.apk"
        echo ::set-output name=versionName::$versionName
        echo ::set-output name=versionCode::$versionCode
    - name: 发布版本
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.apk.outputs.versionName }}-${{ steps.apk.outputs.versionCode }}
        files: |
          ${{ env.OUTPUT_DIR }}/v2er.apk
